### ISSUE TITLE
kryo序列化问题

### ISSUE THREAD

**Issue by simon518** [alibaba/jetcache#125]
使用版本：2.5.1
配置：
jetcache.remote.default.valueEncoder=kryo?useIdentityNumber=false
jetcache.remote.default.valueDecoder=kryo?useIdentityNumber=false
jetcache.local.default.keyConvertor=fastjson

错误堆栈：
jetcache(RedisCache) GET error. key=72.
com.alicp.jetcache.support.CacheEncodeException: decode error
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:46) ~[jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:11) ~[jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.redis.RedisCache.do_GET(RedisCache.java:69) [jetcache-redis-2.5.1.jar!/:?]
        at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:77) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.MultiLevelCache.do_GET(MultiLevelCache.java:88) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:77) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:127) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:102) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:311) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.SimpleProxyCache.computeIfAbsent(SimpleProxyCache.java:93) [jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:168) [jetcache-anno-2.5.1.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92) [jetcache-anno-2.5.1.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84) [jetcache-anno-2.5.1.jar!/:?]
        at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:68) [jetcache-anno-2.5.1.jar!/:?]

中间业务堆栈去掉了！！！

Caused by: com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 72
        at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:137) ~[kryo-4.0.2.jar!/:?]
        at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:693) ~[kryo-4.0.2.jar!/:?]
        at com.esotericsoftware.kryo.Kryo.readClassAndObject(Kryo.java:804) ~[kryo-4.0.2.jar!/:?]
        at com.alicp.jetcache.support.KryoValueDecoder.doApply(KryoValueDecoder.java:31) ~[jetcache-core-2.5.1.jar!/:?]
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:43) ~[jetcache-core-2.5.1.jar!/:?]

**Comment by areyouok** [comment]
从你给出的信息难以判断。

建议使用useIdentityNumber=true兼容性会好一些，改成true以后，再次切换序列化方式的时候不会因为value的不兼容报错，但因为你已经设置false了，刚改成true的时候会出错。
