### ISSUE TITLE
MultiLevelCache报"cannot be cast to com.alicp.jetcache.CacheValueHolder"

### ISSUE THREAD

**Issue by a596620989** [alibaba/jetcache#14]
```
import com.alicp.jetcache.Cache;
import com.alicp.jetcache.MultiLevelCacheBuilder;
import com.alicp.jetcache.embedded.LinkedHashMapCacheBuilder;

import java.util.concurrent.TimeUnit;

/**
 * Created by eros on 2017/9/9.
 */
public class MultiCacheTest {

    public static void main(String args[]){
        String s = multiLevelCache.get(1001L);
        System.out.println(s);
    }

    static String loadFromDb(Long key) {
        return "hahaha";
    }

    static Cache<Long, String> l1Cache = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder()
            .limit(100)
            .expireAfterWrite(200, TimeUnit.SECONDS)
            // 这边调用的时候, 必须要使用强转
            .loader(key -> loadFromDb((Long)key))
            .buildCache();

    static Cache<Long, String> l2Cache = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder()
            .limit(100)
            .expireAfterWrite(200, TimeUnit.SECONDS)
            .loader(key -> loadFromDb((Long)key))
            .buildCache();

    static Cache<Long, String> multiLevelCache = MultiLevelCacheBuilder.createMultiLevelCacheBuilder()
            .addCache(l1Cache, l2Cache)
            .expireAfterWrite(100, TimeUnit.SECONDS)
            .buildCache();
}
```

跑main函数的时候, 会报错

```
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to com.alicp.jetcache.CacheValueHolder
	at com.alicp.jetcache.MultiLevelCache.do_GET(MultiLevelCache.java:57)
	at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:58)
	at com.alicp.jetcache.Cache.get(Cache.java:34)
	at io.terminus.parana.category.service.MultiCacheTest.main(MultiCacheTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by areyouok** [comment]
把loader安装到multiLevelCache上就好了。

技术实现上，MultiLevelCache会完全接管底下的L1、L2级缓存，如果使用了MultiLevelCache，就要一直用它。你如果直接往一级缓存里面put一个值，从multiLevelCache上读是会出错的。

另外从设计上，即使没有上面提到的问题，在一级缓存上安装loader也是没有意义的，设想如果一级缓存内部没有命中，然后它从loader里面加载出来一个值返回，那样二级缓存就没有任何作用了。

下个版本，我在构造MultiLevelCache的时候做个检查好了，如果还有人干了这种事，让错误提示友好些。

**Comment by a596620989** [comment]
给力啊, 立马就看到你的commit了, "Loader on sub cache is not allowed".
"自动load（read through）"这块的文档可以修改下, 强迫症总觉得类型强转看着别扭.

```
Cache<Long,UserDO> userCache = LinkedHashMapCacheBuilder.createLinkedHashMapCacheBuilder()
-                .loader(key -> loadUserFromDatabase(key))
+                .loader((Long key) -> loadUserFromDatabase(key))
                .buildCache();
```

**Comment by areyouok** [comment]
文档昨天我已经改过了，刚才又改了一下
