### ISSUE TITLE
key获取对象中的值,有时候获取不到

### ISSUE THREAD

**Issue by PoppetBrook** [alibaba/jetcache#167]
请问大佬,之前文档说配置javac -parameters是在哪里配置,能说详细点吗
我有2个方法上面都有注解
@CacheInvalidate(name = NAME, key = "#mouldSmart.mouldBasicId")
其中有一个没问题,另外一个报错

org.springframework.expression.spel.SpelEvaluationException: EL1072E: An exception occurred whilst evaluating a compiled expression
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:264)
	at com.alicp.jetcache.anno.method.SpelEvaluator.apply(ExpressionEvaluator.java:136)
	at com.alicp.jetcache.anno.method.ExpressionEvaluator.apply(ExpressionEvaluator.java:70)
	at com.alicp.jetcache.anno.method.ExpressionUtil.lambda$evalKey$5(ExpressionUtil.java:69)
	at com.alicp.jetcache.anno.method.ExpressionUtil.evalKey(ExpressionUtil.java:72)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvalidate(CacheHandler.java:146)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithInvalidateOrUpdate(CacheHandler.java:106)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:94)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.dabanjia.soul.keeper.biz.mould.manager.MouldSmartManager$$EnhancerBySpringCGLIB$$33e7fd6c.update(<generated>)
	at com.dabanjia.soul.keeper.biz.mould.service.MouldSmartServiceImpl.update(MouldSmartServiceImpl.java:63)
	at com.alibaba.dubbo.common.bytecode.Wrapper13.invokeMethod(Wrapper13.java)
	at com.alibaba.dubbo.rpc.proxy.javassist.JavassistProxyFactory$1.doInvoke(JavassistProxyFactory.java:47)
	at com.alibaba.dubbo.rpc.proxy.AbstractProxyInvoker.invoke(AbstractProxyInvoker.java:76)
	at com.alibaba.dubbo.config.invoker.DelegateProviderMetaDataInvoker.invoke(DelegateProviderMetaDataInvoker.java:52)
	at com.alibaba.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at com.alibaba.dubbo.rpc.filter.ExceptionFilter.invoke(ExceptionFilter.java:62)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:75)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.TimeoutFilter.invoke(TimeoutFilter.java:42)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.filter.TraceFilter.invoke(TraceFilter.java:78)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ContextFilter.invoke(ContextFilter.java:72)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.GenericFilter.invoke(GenericFilter.java:131)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.ClassLoaderFilter.invoke(ClassLoaderFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.filter.EchoFilter.invoke(EchoFilter.java:38)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:72)
	at com.alibaba.dubbo.rpc.protocol.dubbo.DubboProtocol$1.reply(DubboProtocol.java:103)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.handleRequest(HeaderExchangeHandler.java:96)
	at com.alibaba.dubbo.remoting.exchange.support.header.HeaderExchangeHandler.received(HeaderExchangeHandler.java:172)
	at com.alibaba.dubbo.remoting.transport.DecodeHandler.received(DecodeHandler.java:51)
	at com.alibaba.dubbo.remoting.transport.dispatcher.ChannelEventRunnable.run(ChannelEventRunnable.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassCastException: com.dabanjia.soul.keeper.api.model.MouldSmart cannot be cast to com.dabanjia.soul.keeper.api.model.MouldSmart
	at spel.Ex3.getValue(Unknown Source)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:254)
	... 42 common frames omitted

**Comment by areyouok** [comment]
这个错误这是你使用了spring dev tools导致的，只会在开发环境出现，升级到最新版本应该可以解决。可以看一下以前有很多这方面的讨论。

-parameters是编译器的设置，在pom里面的编译器插件中设置，ide中在编译器设置的地方设置。

**Comment by PoppetBrook** [comment]
上面那个问题解决了,谢谢大佬,-parameters我发现不加也ok的啊.

**Comment by areyouok** [comment]
如果你没有指定key，jetcache能够根据参数和keyConvertor自动生成key，如果你指定key并且引用了参数名称，是需要加-parameters编译参数的。

**Comment by PoppetBrook** [comment]
我现在是自己指定key了,key引用对象里面的id,例如key="#user.id",但是我没有加-parameters,一样可以,不知道是不是和SpringBoot有关,为了确保我还是加上了,谢谢大佬

**Comment by zhoutaoo** [comment]
key="#user.id",   user父类定义的属性值拿不到 ，这个问题要修复一下吧

**Comment by amuzhou** [comment]
@StoneTiny 如何解决的
