### ISSUE TITLE
 @Cached 不配置cacheType会报空指针异常

### ISSUE THREAD

**Issue by allon2** [alibaba/jetcache#189]
在方法上配置    @Cached(expire = 100)
这样的情况下，会报下面的错误，默认情况下不想使用Remote方法，想默认情况下使用Local，Remote只在配置Remote的情况下生效
Exception in thread "main" java.lang.NullPointerException
 class com.sun.proxy.$Proxy13
	at com.alicp.jetcache.anno.support.CacheContext.buildRemote(CacheContext.java:174)
2018-10-31 10:45:33.396 | main | DEBUG | com.alicp.jetcache.anno.aop.CachePointcut |  |  |  |  |  |  | check method match true: method=getCount, declaringClass=c.c.r.s.RouterProxyService, targetClass=c.c.r.s.i.RouterProxyServiceImpl
	at com.alicp.jetcache.anno.support.CacheContext.buildCache(CacheContext.java:136)
	at com.alicp.jetcache.anno.support.CacheContext.__createOrGetCache(CacheContext.java:120)
	at com.alicp.jetcache.anno.support.CacheContext.createCacheByCachedConfig(CacheContext.java:107)
	at com.alicp.jetcache.anno.support.CacheContext.lambda$createCacheInvokeContext$1(CacheContext.java:79)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:139)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:72)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy13.getCount(Unknown Source)

配置文件如下 
<beans xmlns="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:jetcache="http://www.alibaba.com/schema/jetcache2"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:util="http://www.springframework.org/schema/util" xmlns:aop="http://www.springframework.org/schema/aop"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context-4.1.xsd
        http://www.springframework.org/schema/util  http://www.springframework.org/schema/util/spring-util-4.1.xsd
        http://www.alibaba.com/schema/jetcache2
        http://www.alibaba.com/schema/jetcache/jetcache2.xsd http://www.springframework.org/schema/aop http://www.springframework.org/schema/aop/spring-aop.xsd">
    <context:annotation-config/>
    
    <jetcache:annotation-driven base-package="com.dragon"/>

    <bean id="globalCacheConfig" class="com.alicp.jetcache.anno.support.GlobalCacheConfig">
        <property name="localCacheBuilders">
            <map>
                <entry key="default" value-ref="localCacheBuilder"/>
            </map>
        </property>
        
            
                
            
        
        <property name="configProvider">
            <bean class="com.alicp.jetcache.anno.support.SpringConfigProvider"/>
        </property>
    </bean>
    <bean id="fastjsonKeyConvertor" class="com.alicp.jetcache.support.FastjsonKeyConvertor"/>
    <bean id="localCacheBuilder" class="com.alicp.jetcache.embedded.LinkedHashMapCacheBuilder">
        <property name="keyConvertor" ref="fastjsonKeyConvertor"/>
    </bean>
 

</beans>

**Comment by allon2** [comment]
另外想统一使用cglib，需要怎么配置，目前接口是使用jdkproxy的，在getBean的时候只能使用接口进行调用，无法使用具体类进行调用

**Comment by allon2** [comment]
目前框架都是使用的xml配置，没使用注解方法，还希望给一个xml的配置例子

**Comment by noachianark** [comment]
能以yml配置方式指定默认的CacheType吗
