### ISSUE TITLE
序列化是否支持泛型？

### ISSUE THREAD

**Issue by zhongweng** [alibaba/jetcache#198]
泛型：
@Data
@NoArgsConstructor
public class EchartDataWrapperRes<K, T> implements Serializable{

    @ApiModelProperty(value = "key")
    private K key;
    @ApiModelProperty(value = "name")
    private String name;
    @ApiModelProperty(value = "data")
    private T data;
    ...
}
com.alicp.jetcache.support.CacheEncodeException: Java Encode error. msg=com.meituan.hotel.mint.model.result.mint.finance.EchartMdlKeyValRes
	at com.alicp.jetcache.support.JavaValueEncoder.apply(JavaValueEncoder.java:63)
	at com.alicp.jetcache.support.JavaValueEncoder.apply(JavaValueEncoder.java:13)
	at com.meituan.hotel.cachekeeper.cellar.CellarCache.do_PUT(CellarCache.java:181)
	at com.alicp.jetcache.AbstractCache.PUT(AbstractCache.java:223)
	at com.alicp.jetcache.Cache.PUT(Cache.java:366)
	at com.alicp.jetcache.Cache.put(Cache.java:74)

**Comment by areyouok** [comment]
com.meituan.hotel.mint.model.result.mint.finance.EchartMdlKeyValRes
这个类没有实现序列化接口吧

**Comment by areyouok** [comment]
你可以去了解一下Java的序列化机制。
