### ISSUE TITLE
和携程的apollo配置中心结合报com.alicp.jetcache.CacheConfigException: no remote cache builder: default

### ISSUE THREAD

**Issue by ZEROyongyong** [alibaba/jetcache#210]
去除apollo配置中心 则不抛此异常
at com.alicp.jetcache.anno.support.CacheContext.buildRemote(CacheContext.java:176)
	at com.alicp.jetcache.anno.support.CacheContext.buildCache(CacheContext.java:136)
	at com.alicp.jetcache.anno.support.CacheContext.__createOrGetCache(CacheContext.java:122)
	at com.alicp.jetcache.anno.support.CacheContext.createCacheByCachedConfig(CacheContext.java:107)
	at com.alicp.jetcache.anno.support.CacheContext.lambda$createCacheInvokeContext$1(CacheContext.java:79)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:139)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:72)

**Comment by areyouok** [comment]
这是配置错误，你再看看？

**Comment by Jason1220** [comment]
@ZEROyongyong  你的问题有解决吗，我使用Apollo时也发现相同的错误，测试感觉不是配置问题

@areyouok 请再看一下此问题，使用Apollo时不会初始化RedisAutoConfiguration

**Comment by areyouok** [comment]
see #219
