### ISSUE TITLE
加上@CachePenetrationProtect注解后可能导致请求被一直挂起

### ISSUE THREAD

**Issue by amit-gshe** [alibaba/jetcache#234]
```    
    @Cached(name = "UserService.queryUserInfo", expire = 3)
    @CachePenetrationProtect
    fun queryUserInfo(account: String): User?
```
如题, 当我加上`@CachePenetrationProtect`注解后请求会被一直等待, 去掉之后就能返回正常结果
通过debug后发现`com.alicp.jetcache.AbstractCache#synchronizedLoad()`会被执行两次, 第二次执行之后一直等待在`ll.signal.await();` 两次执行的堆栈信息如下:
```
"http-nio-8080-exec-1@15936" daemon prio=5 tid=0x3e nid=NA runnable
  java.lang.Thread.State: RUNNABLE
--->	  at com.alicp.jetcache.AbstractCache.synchronizedLoad(AbstractCache.java:188)
	  at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:153)
	  at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:111)
	  at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:311)
	  at com.alicp.jetcache.SimpleProxyCache.computeIfAbsent(SimpleProxyCache.java:93)
	  at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:245)
	  at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92)
	  at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84)
	  at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:72)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	  at com.channeljin.hotpot.service.ShopUserAdminServiceImpl$$EnhancerBySpringCGLIB$$9eda3e25.queryUserInfo(<generated>:-1)
	  at com.channeljin.hotpot.common.service.AbstractUserServiceImpl$$FastClassBySpringCGLIB$$3214cb1d.invoke(<generated>:-1)
	  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	  at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	  at org.springframework.transaction.interceptor.TransactionInterceptor$$Lambda$1170.912769873.proceedWithInvocation(Unknown Source:-1)
	  at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294)
	  at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	  at com.alicp.jetcache.anno.aop.JetCacheInterceptor$$Lambda$1160.1860306852.invoke(Unknown Source:-1)
	  at com.alicp.jetcache.anno.method.CacheHandler.invokeOrigin(CacheHandler.java:278)
	  at com.alicp.jetcache.anno.method.CacheHandler.access$000(CacheHandler.java:21)
	  at com.alicp.jetcache.anno.method.CacheHandler$1.load(CacheHandler.java:235)
	  at com.alicp.jetcache.CacheLoader.apply(CacheLoader.java:31)
	  at com.alicp.jetcache.CacheUtil.lambda$createProxyLoader$0(CacheUtil.java:70)
	  at com.alicp.jetcache.CacheUtil$$Lambda$1165.410794416.apply(Unknown Source:-1)
--->	  at com.alicp.jetcache.AbstractCache.synchronizedLoad(AbstractCache.java:177)
	  at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:153)
	  at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:111)
	  at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:311)
	  at com.alicp.jetcache.SimpleProxyCache.computeIfAbsent(SimpleProxyCache.java:93)
	  at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:245)
	  at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92)
	  at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84)
	  at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:72)
	  at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	  at com.channeljin.hotpot.service.ShopUserAdminServiceImpl$$EnhancerBySpringCGLIB$$f43cdbd9.queryUserInfo(<generated>:-1)
	  at com.channeljin.hotpot.web.ShopUserAdminController.getUserInfo(ShopUserAdminController.kt:58)
	  at com.channeljin.hotpot.web.ShopUserAdminController$$FastClassBySpringCGLIB$$25ebb3bf.invoke(<generated>:-1)
	  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	  at com.channeljin.hotpot.web.ShopUserAdminController$$EnhancerBySpringCGLIB$$4f60ed8c.getUserInfo(<generated>:-1)
	  at com.channeljin.hotpot.web.ShopUserAdminController$$FastClassBySpringCGLIB$$25ebb3bf.invoke(<generated>:-1)
	  at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	  at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	  at com.channeljin.hotpot.web.ShopUserAdminController$$EnhancerBySpringCGLIB$$561a5834.getUserInfo(<generated>:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	  at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	  at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	  at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	  at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	  at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	  at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	  at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	  at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	  at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at com.lerjin.common.filter.LoggingFilter.doFilterInternal(LoggingFilter.java:21)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	  at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	  at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	  at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	  at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	  at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	  at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	  at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	  at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	  at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	  at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	  at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	  at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	  at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	  at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	  at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	  at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	  - locked <0x4155> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	  at java.lang.Thread.run(Thread.java:745)
```

**Comment by areyouok** [comment]
看了一下代码没有发现什么问题，synchronizedLoad在你的栈中出现了两次，是两个不同的方法，方法1没有命中缓存，然后执行原始方法，此时又调用了方法2

**Comment by areyouok** [comment]
需要更多信息

**Comment by amit-gshe** [comment]
```
            if (create[0]) {
                try {
                    loadedValue = newLoader.apply(key);
                    ll.success = true;
                    ll.value = loadedValue;
                    cacheUpdater.accept(loadedValue);
                    break;
                } finally {
                    loaderMap.remove(lockKey);
                    ll.signal.countDown();
                }
            } else {
                try {
                    ll.signal.await();
                    if (ll.success) {
                        loadedValue = (V) ll.value;
                        break;
                    } else {
                        continue;
                    }
                } catch (InterruptedException e) {
                    throw new CacheException("loader wait interrupted", e);
                }
}
```
在这个方法中第一次·`if (create[0])`是`true`, 然后第二次又走到这时，` if (create[0])`成了false, 之后就wait在`ll.signal.await()`了，不知道为什么第一次`loadedValue = newLoader.apply(key);`之后为什么又走回来了，然后`loadedValue`一直没有算出来。

**Comment by areyouok** [comment]
你应该看看是哪个别的线程把它锁住了，你在调试的时候其它线程都是挂起的。

**Comment by amit-gshe** [comment]
原因找到了, 我的应用中有两个`AdvisorAutoProxyCreator`,首先由默认由spring boot 创建的`AnnotationAwareAspectJAutoProxyCreator`创建了一层内层代理, 然后shiro-spring-boot-starter创建的`DefaultAdvisorAutoProxyCreator`又对前面创建的代理对象再次生成了一层外层代理, 在调用外层代理的时候没有命中缓存, 然后又调内层代理对象去获取值此时就引发了上面`if (create[0])`为`false` 并且`ll.signal.await()`, 这个过程中只涉及到一个线程, 也就是说`synchronizedLoad`在嵌套代理时可能导致同步锁一直无法释放.

**Comment by areyouok** [comment]
感谢提供的信息，我已经修改了，可以用最新的master打个snapshot包试试，当前master是稳定的。

针对同一个线程自己锁住自己的问题，我之前也想过，但是觉得一个key的loader加载过程中又去加载这个key本身是不应该的，就没继续改。

另外，你关联的问题可能是另一个问题。

**Comment by amit-gshe** [comment]
我今天试了最新的2.5.11-SNAPSHOT, 问题解决了

**Comment by areyouok** [comment]
同一个方法被cache两次是不对的，我昨天也改了一下，方便的话帮我看看现在是否不cache两次了

https://github.com/alibaba/jetcache/commit/e92cef36e8e7c563b18702a682727312e4cffc18

**Comment by amit-gshe** [comment]
我调试后发现`com.alicp.jetcache.anno.aop.CachePointcut.matchesImpl(Class clazz)`无法检查出代理对象:
```
    private boolean matchesImpl(Class clazz) {
        if (matchesThis(clazz)) { // 这里能检查出代理对象, matches是false, 但结果被忽略了
            return true;
        }
        Class[] cs = clazz.getInterfaces();
        if (cs != null) {
            for (Class c : cs) {
                if (matchesImpl(c)) {
                    return true;
                }
            }
        }
        if (!clazz.isInterface()) {
            Class sp = clazz.getSuperclass(); // 代理对象的父对象是被代理对象, 所以匹配成功
            if (sp != null && matchesImpl(sp)) {
                return true;
            }
        }
        return false;
    }
```

**Comment by areyouok** [comment]
你第二行注释不对，应该是“代理对象的父对象*不是*被代理对象, 所以匹配成功”

虽然你贴的这个方法会放过去，不过还有个public boolean matches(Method method, Class targetClass)方法，这个方法会拦住的。

**Comment by amit-gshe** [comment]
是的，调用栈和最开始一样，只是现在不会被挂起了

**Comment by amit-gshe** [comment]
我写了个[demo](https://github.com/amit-gshe/jetcache_234), 你看看有没有帮助。

**Comment by areyouok** [comment]
感谢提供的线索，我周末看看

**Comment by areyouok** [comment]
改了一下，现在只代理一次了。

**Comment by areyouok** [comment]
2.5.11版本已经发布
