### ISSUE TITLE
ClassCastException cacheType=BOTH后，有时候会报错.

### ISSUE THREAD

**Issue by craftsman-li** [alibaba/jetcache#24]
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.alicp.jetcache.CacheValueHolder
	at com.alicp.jetcache.MultiLevelCache.do_GET(MultiLevelCache.java:57)
	at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:58)
	at com.alicp.jetcache.RefreshCache.GET(RefreshCache.java:107)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCache(CacheHandler.java:131)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:106)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:99)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:69)

**Comment by areyouok** [comment]
从这些信息不好判断。能否重现？最近是不是升级过jetcache的版本？

**Comment by areyouok** [comment]
我明白了，因为从REMOTE修改为BOTH以后，MultiLevelCache会多包装一层，导致旧的程序put到远程缓存中的数据新的程序读不出来。

抛出异常造成的效果等于是缓存没有命中，没有别的影响。这个问题我看看能不能优化。

**Comment by craftsman-li** [comment]
ok,,谢谢了，那可能是我本地改了BOTH，日常还在用REMOTE导致的，谢谢

**Comment by areyouok** [comment]
改了以后你换个name就不会冲突了。

**Comment by areyouok** [comment]
这个错误会导致向上层业务代码抛出异常，不像我上面说的那样没有影响，我会在近几天修复它。

**Comment by areyouok** [comment]
已经在2.4和2.3.4版本中修复。
