### ISSUE TITLE
JetCache 启动时显示与xxl-job有冲突

### ISSUE THREAD

**Issue by YeLuoXu** [alibaba/jetcache#244]
我项目使用了xxl-job，现在缓存框架换JetCache时，启动时产生如下异常，麻烦看一下
``` java
CaffeineAutoConfiguration init
2019-01-29 14:19:24.111  INFO 761980 --- [           main] c.a.j.a.AbstractCacheAutoInit            : init cache area default , type= caffeine
2019-01-29 14:19:24.141  INFO 761980 --- [           main] c.a.j.a.AbstractCacheAutoInit            : init cache area default , type= redis.lettuce
2019-01-29 14:19:24.172  WARN 761980 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisLettuceAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: reactor/core/scheduler/Schedulers
2019-01-29 14:19:24.179 ERROR 761980 --- [      Thread-86] c.x.j.c.thread.ExecutorRegistryThread    : sleep interrupted

java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at java.lang.Thread.sleep(Thread.java:340)
	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
	at com.xxl.job.core.thread.ExecutorRegistryThread$1.run(ExecutorRegistryThread.java:75)
	at java.lang.Thread.run(Thread.java:748)

2019-01-29 14:19:24.191 ERROR 761980 --- [      Thread-87] c.x.j.core.thread.TriggerCallbackThread  : null

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.xxl.job.core.thread.TriggerCallbackThread$1.run(TriggerCallbackThread.java:55)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by YeLuoXu** [comment]
仔细看了下，好像是由于io.lettuce.core.resource.DefaultClientResources类缺少Jar包导致的
import reactor.core.scheduler.Schedulers;
