### ISSUE TITLE
关于Redis集群如何配置uri的问题

### ISSUE THREAD

**Issue by ASCE1885** [alibaba/jetcache#300]
通过 JetCache 连接 redis 集群，spring boot 配置文件内容如下：

```properties
jetcache.areaInCacheName=false
jetcache.hidePackages=com.hust.asce
jetcache.remote.default.keyConvertor=fastjson
jetcache.remote.default.type=redis.lettuce
jetcache.remote.default.uri[0]=redis://127.0.0.1:16380
jetcache.remote.default.uri[1]=redis://127.0.0.1:16381
jetcache.remote.default.uri[2]=redis://127.0.0.1:16382
jetcache.remote.default.valueDecoder=kryo
jetcache.remote.default.valueEncoder=kryo
jetcache.statIntervalMinutes=15
```

启动时，报错如下所示

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisLettuceAutoConfiguration.class]: Invocation of init method failed; nested exception is io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='10.25.80.12', port=16381], RedisURI [host='10.25.80.12', port=16382], RedisURI [host='10.25.80.12', port=16380]]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:849) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) ~[spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar:2.1.4.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:13) [classes/:na]
Caused by: io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='10.25.80.12', port=16381], RedisURI [host='10.25.80.12', port=16382], RedisURI [host='10.25.80.12', port=16380]]
	at io.lettuce.core.cluster.RedisClusterClient.doLoadPartitions(RedisClusterClient.java:874) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.cluster.RedisClusterClient.loadPartitions(RedisClusterClient.java:844) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.cluster.RedisClusterClient.initializePartitions(RedisClusterClient.java:819) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at io.lettuce.core.cluster.RedisClusterClient.connect(RedisClusterClient.java:345) ~[lettuce-core-5.1.6.RELEASE.jar:na]
	at com.alicp.jetcache.redis.lettuce.LettuceConnectionManager.connection(LettuceConnectionManager.java:65) ~[jetcache-redis-lettuce-2.5.12.jar:na]
	at com.alicp.jetcache.autoconfigure.RedisLettuceAutoConfiguration$RedisLettuceAutoInit.initCache(RedisLettuceAutoConfiguration.java:121) ~[jetcache-autoconfigure-2.5.12.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.process(AbstractCacheAutoInit.java:68) ~[jetcache-autoconfigure-2.5.12.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.afterPropertiesSet(AbstractCacheAutoInit.java:49) ~[jetcache-autoconfigure-2.5.12.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 16 common frames omitted
```

redis 单节点时没问题

**Comment by areyouok** [comment]
应该是你的cluster没配置好。

**Comment by ASCE1885** [comment]
这个问题的原因是Redis集群设置了密码，jetcache访问时指定密码就可以了：

```
jetcache.remote.default.uri[0]=redis://password@127.0.0.1:16380
jetcache.remote.default.uri[1]=redis://password@127.0.0.1:16381
jetcache.remote.default.uri[2]=redis://password@127.0.0.1:16382
```

使用文档里面建议增加下uri配置遵循 [Lettuce RedisURI](https://github.com/lettuce-io/lettuce-core/wiki/Basic-usage#redisuri) 格式的说明。

而且出错的异常提示也比较奇怪。
