### ISSUE TITLE
缓存自动刷新抛异常

### ISSUE THREAD

**Issue by Refractaire** [alibaba/jetcache#325]
com.alicp.jetcache.CacheException: refresh error
        at com.alicp.jetcache.RefreshCache$RefreshTask.lambda$externalLoad$0(RefreshCache.java:188)
        at com.alicp.jetcache.Cache.tryLockAndRun(Cache.java:272)
        at com.alicp.jetcache.RefreshCache$RefreshTask.externalLoad(RefreshCache.java:193)
        at com.alicp.jetcache.RefreshCache$RefreshTask.run(RefreshCache.java:233)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No MethodInvocation found: Check that an AOP invocation is in progress, and that the ExposeInvocationInterceptor is upfront in the interceptor chain. Specifically, note that advices with order HIGHEST_PRECEDENCE will execute before ExposeInvocationInterceptor!
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.currentInvocation(ExposeInvocationInterceptor.java:73)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.getJoinPointMatch(AbstractAspectJAdvice.java:652)
        at org.springframework.aop.aspectj.AspectJMethodBeforeAdvice.before(AspectJMethodBeforeAdvice.java:43)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:51)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at com.alicp.jetcache.anno.method.CacheHandler.invokeOrigin(CacheHandler.java:278)
        at com.alicp.jetcache.anno.method.CacheHandler.access$000(CacheHandler.java:21)
        at com.alicp.jetcache.anno.method.CacheHandler$1.load(CacheHandler.java:235)
        at com.alicp.jetcache.CacheUtil$1.load(CacheUtil.java:29)
        at com.alicp.jetcache.RefreshCache$RefreshTask.load(RefreshCache.java:151)
        at com.alicp.jetcache.RefreshCache$RefreshTask.lambda$externalLoad$0(RefreshCache.java:184)
        ... 10 common frames omitted

jecache版本:2.5.12.
springboot版本1.4.4.

**Comment by areyouok** [comment]
这个错误的意思是，ExposeInvocationInterceptor需要是优先级最高的aop拦截器。你可以阅读相关javadoc：

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/aop/interceptor/ExposeInvocationInterceptor.html

拦截器有很多层，默认情况下jetcache的拦截器优先级是最低的，自动刷新的时候，jetcache其实是把当时的methodInvocation::proceed句柄保存下来反复使用的，如果它内层还有AOP拦截器，并且这些AOP拦截器依赖了外层AOP拦截器设置的状态的话，就会读不到。

可以通过调整AOP顺序（Order），保证jetcache的拦截器在最内层。或者用CreateCache注解生成的Cache实例来做自动刷新，这样不会有AOP问题。

另外也可以参考这里：
https://github.com/alibaba/jetcache/issues/161
