### ISSUE TITLE
序列化器是否验证过gson

### ISSUE THREAD

**Issue by edhn3000** [alibaba/jetcache#333]
参照wiki和问题https://github.com/alibaba/jetcache/issues/34
fastjson在序列化反序列化中的问题，gson是否也存在，是否用gson跑过官方测试用例。gson本身兼容性比较好，如果不存在fastjson的问题，官方可否提供一个gson的序列化器

**Comment by areyouok** [comment]
没有哪个序列化/反序列化器可以保证序列化/反序列化每一个Java类，就算是兼容性最好的Java内置序列化机制，也要求业务类实现Serializable接口才行（就这还有人问为什么JetCache没有序列化我的类。。。）

对使用方来说，能不能跑过测试用例不重要，关键是能不能序列化/反序列化我的类？

有这个需求暂且先自己定制吧，定制这个还是很容易的。
2.6版本，直接在Spring Context中提供一个EncoderParser实例就可以了。然后yml里面可以指定默认的valueEncoder和valueDecoder。
2.6之前的版本， 提供一个自己的SpringConfigProvider实例，覆盖parseValueEncoder和parseValueDecoder方法。然后yml里面可以指定默认的valueEncoder和valueDecoder。

**Comment by edhn3000** [comment]
2.6.0M3版，使用EncoderParser配置序列化器，部分代码如下
`@Configuration
@AutoConfigureBefore(JetCacheAutoConfiguration.class)
public class JetCacheConfiguration {
    
    @Bean
    public EncoderParser gsonSupportedEncoderParser() {
        return new DefaultEncoderParser() {
            @Override
            public Function<Object, byte[]> parseEncoder(String valueEncoder) {
                URI uri = URI.create(StringUtils.stripToEmpty(valueEncoder));
                String encoder = uri.getPath();
                boolean useIdentityNumber = Optional.ofNullable(uri.getQuery())
                        .map(q -> parseQueryParameters(q))
                        .map(m -> "true".equalsIgnoreCase(m.get("useIdentityNumber"))).orElse(false);
                if ("gson".equals(encoder)) {
                    return new GsonValueEncoder(useIdentityNumber);
                } else if ("fastjson".equals(encoder)) {
                    return new FastjsonValueEncoder(useIdentityNumber);
                } else {
                    return super.parseEncoder(valueEncoder);
                }
            }
...
`
在使用lettuce客户端连redis时启动有错误，使用jedis客户端正常
lettuce报错

`Caused by: com.alicp.jetcache.CacheConfigException: not supported:gson
	at com.alicp.jetcache.anno.support.DefaultEncoderParser.parseEncoder(DefaultEncoderParser.java:60) ~[jetcache-anno-2.6.0.M3.jar:na]
	at com.alicp.jetcache.anno.support.DefaultSpringEncoderParser.parseEncoder(DefaultSpringEncoderParser.java:38) ~[jetcache-anno-2.6.0.M3.jar:na]
	at com.alicp.jetcache.anno.support.ConfigProvider.parseValueEncoder(ConfigProvider.java:74) ~[jetcache-anno-2.6.0.M3.jar:na]
	at com.alicp.jetcache.autoconfigure.ExternalCacheAutoInit.parseGeneralConfig(ExternalCacheAutoInit.java:22) ~[jetcache-autoconfigure-2.6.0.M3.jar:na]
	at com.alicp.jetcache.autoconfigure.RedisLettuceAutoConfiguration$RedisLettuceAutoInit.initCache(RedisLettuceAutoConfiguration.java:115) ~[jetcache-autoconfigure-2.6.0.M3.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.process(AbstractCacheAutoInit.java:68) ~[jetcache-autoconfigure-2.6.0.M3.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.afterPropertiesSet(AbstractCacheAutoInit.java:49) ~[jetcache-autoconfigure-2.6.0.M3.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	... 45 common frames omitted
`
RedisLettuceAutoInit.initCache比SpringConfigProvider.setEncoderParser(EncoderParser) 更早触发，不会用到自定义的EncodeParser，使用jedis客户端（即引入jetcache-starter-redis）是正常的

**Comment by areyouok** [comment]
你提供的是SpringConfigProvider吗？

RedisLettuceAutoInit这个bean依赖了ConfigProvider（通过autowired），没理由它初始化的时候ConfigProvider还没有初始化。

**Comment by edhn3000** [comment]
上边报错时是按2.6的方式只提供EncoderParser实例时产生的，现在我使用2.5的方式提供SpringConfigProvider实例先解决。
感觉问题是RedisLettuceAutoInit这个内部静态类其中initCache这里子方法过早的使用了configProvider.parseValueEncoder，还没有被spring注入自定义的EncoderParser

**Comment by CrossIce** [comment]
asda
