### ISSUE TITLE
手动缓存时候的API直接报错！

### ISSUE THREAD

**Issue by CodingOX** [alibaba/jetcache#374]
我利用API:
`Cache cityCache = CacheManager.defaultManager().getCache("xxx");`
手动获取缓存来remove的时候，当这个缓存不存在的时候，API直接抛了异常，是否考虑下，返回一个NULL或者通过其他更好的方式处理！

**Comment by areyouok** [comment]
什么异常？

**Comment by CodingOX** [comment]
应该是获取的时候报错，信息如下
```
java.lang.IllegalArgumentException: cache definition not found: area=default,cacheName=hct:
	at com.alicp.jetcache.anno.method.SpringCacheContext.lambda$init$0(SpringCacheContext.java:34)
	at com.alicp.jetcache.anno.support.SimpleCacheManager.getCache(SimpleCacheManager.java:51)
	at com.alicp.jetcache.anno.support.CacheManager.getCache(CacheManager.java:16)
```

**Comment by areyouok** [comment]
提供CacheManager是为了更加方便的获取到Cached注解生成的Cache实例，但现在它是懒加载的，所以你这里有可能会获取不到。

**Comment by CodingOX** [comment]
> 提供CacheManager是为了更加方便的获取到Cached注解生成的Cache实例，但现在它是懒加载的，所以你这里有可能会获取不到。

我当前的情况是否`懒加载`无关，是我无法确定这个缓存是否存在，但是我为了保证数据的及时性，每次必须清楚，所以在没有事先建立缓存的情况下，调用这个获取方法报错。
现在是手动`try`了下，但是感觉不优雅。
API层面能否做更好的处理，比如返回`NULL`或存在才删除这样的逻辑！？

**Comment by areyouok** [comment]
返回null很容易，但我需要先评估一下影响
