### ISSUE TITLE
CacheValueHolder class not found  求解

### ISSUE THREAD

**Issue by DavidFranck** [alibaba/jetcache#389]
我使用spring cloud 2.1.3.RELEASE 版本 实体类 缓存service 在父模块中 依赖也都在父极pom。两个模块引用同一个父极，其中一个模块可以正常使用 另一个不可以 回报class not fund 这个是为什么呢？

2019-11-14 17:51:51,933 [ForkJoinPool.commonPool-worker-21] ERROR [com.alicp.jetcache.AbstractCache] AbstractCache.java:52 - jetcache(RedisCache) GET error. key=1363.
com.alicp.jetcache.support.CacheEncodeException: decode error
	at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:46)
	at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:11)
	at com.alicp.jetcache.redis.RedisCache.do_GET(RedisCache.java:108)
	at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:91)
	at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:147)
	at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:122)
	at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:312)
	at com.alicp.jetcache.SimpleProxyCache.computeIfAbsent(SimpleProxyCache.java:93)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:246)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:93)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:85)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:93)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at com.tyrise.sagittarius.service.AccountService$$EnhancerBySpringCGLIB$$e3b1b1ec.getById(<generated>)
	at com.tyrise.sagittarius.sdk.MediaTokenStore.getAccessToken(MediaTokenStore.java:81)
	at com.tyrise.sagittarius.sdk.MediaTokenStore$$FastClassBySpringCGLIB$$19d8925d.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.tyrise.sagittarius.sdk.MediaTokenStore$$EnhancerBySpringCGLIB$$c654ee8.getAccessToken(<generated>)
	at com.tyrise.sagittarius.service.ToutiaoSyncTaskService.syncCreativeReport(ToutiaoSyncTaskService.java:203)
	at com.tyrise.sagittarius.service.ToutiaoSyncTaskService$$FastClassBySpringCGLIB$$62b07bec.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:684)
	at com.tyrise.sagittarius.service.ToutiaoSyncTaskService$$EnhancerBySpringCGLIB$$f519c683.syncCreativeReport(<generated>)
	at com.tyrise.sagittarius.task.SyncTask.lambda$toutiaoSyncTaskService$4(SyncTask.java:206)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.ClassNotFoundException: com.alicp.jetcache.CacheValueHolder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:275)
	at org.springframework.core.ConfigurableObjectInputStream.resolveClass(ConfigurableObjectInputStream.java:76)
	at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1886)
	at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1772)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2060)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1594)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
	at com.alicp.jetcache.support.JavaValueDecoder.doApply(JavaValueDecoder.java:29)
	at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:41)
	... 37 common frames omitted

**Comment by areyouok** [comment]
这可能需要你自己来解决，看看是不是和spring dev tools有关

**Comment by hjjoe1213123** [comment]
不用纠结，jetcache的BUG
可以看到在jdk11环境下，ForkJoinPool创建的线程对应的classloader为 ClassLoader.getSystemClassLoader()， ClassLoader.getSystemClassLoader()默认返回jdk.internal.loader.ClassLoaders.AppClassLoader。jdk.internal.loader.ClassLoaders.AppClassLoader加载的范围是classpath，所以没有找到 fatjar 下面的类。如果要能够加载spring boot fatjar里的类， 则需要SpringBoot 的LaunchedURLClassLoader

**Comment by davids-dot** [comment]
> 不用纠结，jetcache的BUG 可以看到在jdk11环境下，ForkJoinPool创建的线程对应的classloader为 ClassLoader.getSystemClassLoader()， ClassLoader.getSystemClassLoader()默认返回jdk.internal.loader.ClassLoaders.AppClassLoader。jdk.internal.loader.ClassLoaders.AppClassLoader加载的范围是classpath，所以没有找到 fatjar 下面的类。如果要能够加载spring boot fatjar里的类， 则需要SpringBoot 的LaunchedURLClassLoader

大佬厉害，在应用程序里怎么修改可以避免这个错误啊

**Comment by JabinHao** [comment]
不要用ForkJoinPool，创建自定义线程池的时候指定类加载器应该就解决了

> > 不用纠结，jetcache的BUG 可以看到在jdk11环境下，ForkJoinPool创建的线程对应的classloader为 ClassLoader.getSystemClassLoader()， ClassLoader.getSystemClassLoader()默认返回jdk.internal.loader.ClassLoaders.AppClassLoader。jdk.internal.loader.ClassLoaders.AppClassLoader加载的范围是classpath，所以没有找到 fatjar 下面的类。如果要能够加载spring boot fatjar里的类， 则需要SpringBoot 的LaunchedURLClassLoader
> 
> 大佬厉害，在应用程序里怎么修改可以避免这个错误啊

不要用ForkJoinPool，创建自定义线程池的时候指定类加载器应该就解决了

**Comment by niuchang3** [comment]
> 不用纠结，jetcache的BUG 可以看到在jdk11环境下，ForkJoinPool创建的线程对应的classloader为 ClassLoader.getSystemClassLoader()， ClassLoader.getSystemClassLoader()默认返回jdk.internal.loader.ClassLoaders.AppClassLoader。jdk.internal.loader.ClassLoaders.AppClassLoader加载的范围是classpath，所以没有找到 fatjar 下面的类。如果要能够加载spring boot fatjar里的类， 则需要SpringBoot 的LaunchedURLClassLoader

使用ForkJoinPool创建线程池,我本地没能复现....能请教下如何复现这个问题吗
