### ISSUE TITLE
5u7升级7u2之后，JetCacheInterceptor抛空指针

### ISSUE THREAD

**Issue by aslldab1** [alibaba/jetcache#393]
具体堆栈如下，排查了好久都想不到什么原因：
java.lang.NullPointerException: null
        at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:65)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy179.getRelationByAliUid(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor258.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by aslldab1** [comment]
应用代码没有变更过，只是系统镜像从5u7升级到7u2

**Comment by aslldab1** [comment]
依赖版本是：
<dependency>
				<groupId>com.alicp.jetcache</groupId>
				<artifactId>jetcache-anno</artifactId>
				<version>2.5.7</version>
			</dependency>

**Comment by areyouok** [comment]
这个版本太老了，我不知道这代表哪一行，可能jdk变了，也可能有其它环境变化
