### ISSUE TITLE
使用阿里云的Redis查询异常

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#425]
使用PUT时没报错，然后使用GET获取值是提示：
```
[FAIL]class java.util.concurrent.TimeoutException:null
```
但是阿里云后台是可以连上Redis的，
重启Redis之后5分钟又好了。
现在不清楚是jetcache的问题还是阿里云Redis的问题

**Comment by areyouok** [comment]
给出的信息不足，无法判断

**Comment by Skqing** [comment]
```
2019-12-27 13:02:57.801 [JetCacheDefaultExecutor] ERROR [com.alicp.jetcache.AbstractCache.logError: 52] - jetcache(RedisLettuceCache) GET error. key=07202790775006798275772197668209.
java.lang.IllegalStateException: null
	at io.lettuce.core.output.CommandOutput.set(CommandOutput.java:85) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:358) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:139) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:716) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:680) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:666) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:596) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:565) ~[lettuce-core-5.2.1.RELEASE.jar!/:5.2.1.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514) ~[netty-transport-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1050) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.43.Final.jar!/:4.1.43.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

时不时会报这个异常。
```
2019-12-27 13:14:02.517 [http-nio-8282-exec-2] INFO [com.alicp.jetcache.Cache.tryLock: 221] - [tryLock] [1 of 2] [2acef71c-b7c5-441e-835e-1c6b0a1ed37e] cache access failed during get lock, will inquiry 1 times. Key=findFormDbLock, msg=class java.util.concurrent.TimeoutException:null
2019-12-27 13:14:03.517 [http-nio-8282-exec-2] INFO [com.alicp.jetcache.Cache.tryLock: 238] - [tryLock] [1 of 1] [2acef71c-b7c5-441e-835e-1c6b0a1ed37e] inquiry failed. Key=findFormDbLock, msg=class java.util.concurrent.TimeoutException:null
2019-12-27 13:14:04.518 [http-nio-8282-exec-2] INFO [com.alicp.jetcache.Cache.tryLock: 221] - [tryLock] [2 of 2] [2acef71c-b7c5-441e-835e-1c6b0a1ed37e] cache access failed during get lock, will inquiry 1 times. Key=findFormDbLock, msg=class java.util.concurrent.TimeoutException:null
2019-12-27 13:14:05.519 [http-nio-8282-exec-2] INFO [com.alicp.jetcache.Cache.tryLock: 238] - [tryLock] [1 of 1] [2acef71c-b7c5-441e-835e-1c6b0a1ed37e] inquiry failed. Key=findFormDbLock, msg=class java.util.concurrent.TimeoutException:null
```

**Comment by Skqing** [comment]
问题是此时阿里云后台是能连上Redis并且正常操作KEY的。然后重启阿里云的Redis几分钟之后服务就又正常了，很奇怪。

**Comment by HeroOnline** [comment]
JetCache技术交流，钉钉群： 21914454

**Comment by Skqing** [comment]
今天又出现这个问题了，唉，是不是Jetcache不稳定呢？
```
[FAIL]class java.util.concurrent.TimeoutException:null
```
只有这一行错误提示，没有更多信息，唉纠结。

**Comment by Skqing** [comment]
是不是lettuce还不够文档呢？

    lettuce只要断掉连接后，自己并没有去重连的机制，最后导致time out。不知是否与连接实例有关、又或者是lettuce bug？

**Comment by Skqing** [comment]
lettuce 如何设置超时时间呢？文档里没有写啊

**Comment by Skqing** [comment]
隔一段时间就出现这个问题，很烦人啊，重启阿里云Redis就又好了，唉！

**Comment by areyouok** [comment]
既然决定用lettuce，首先应该先去看lettuce的文档，各种属性包括超时时间怎么设置它的文档里面都是有的。

遇到问题先搜索一下，用IllegalStateException去lettuce的issue列表里面搜索，很快就能找到编号是1151的那个issue，和你的一模一样。

建议你如果需要自己连接lettuce使用其它api的话，可以自己获取client和connection试试，不要用Cache接口unwrap出来的东西。lettuce是一个支持异步模型的client，对开发能力要求很高，一不小心就把整个连接都搞坏了。

**Comment by Skqing** [comment]
好吧，多谢大佬指点，我再研究研究。另外问一下大佬这个jetcache未来路线是怎样的，为什么不做一个网站主页呢，还有类似dubbo官网一样以及文档，那样岂不是更好。本人能力有限，但是可以参与到文档修改和编写上啊！不知道大佬怎么打算。

**Comment by jjwfk** [comment]
能问一下大哥最后这个问题是怎么配置解决的吗？ @Skqing

**Comment by Skqing** [comment]
> 能问一下大哥最后这个问题是怎么配置解决的吗？ @Skqing

应该是某个地方错误导致链接断掉导致Lettuce客户端都不能用了，时间很长了，具体忘了怎么弄的了
