### ISSUE TITLE
项目使用redis集群配置jetcache，启动出这种问题，翻译是依赖的问题

### ISSUE THREAD

**Issue by XyCodeer** [alibaba/jetcache#449]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisLettuceAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/alicp/jetcache/redis/lettuce/RedisLettuceCacheBuilder
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar!/:2.0.4.RELEASE]
	at com.fehorizon.saasService.user.UserCenterApplication.main(UserCenterApplication.java:29) [classes!/:2.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_231]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_231]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [user-center-6bee672b-25-20200228152717.jar:2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [user-center-6bee672b-25-20200228152717.jar:2.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [user-center-6bee672b-25-20200228152717.jar:2.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [user-center-6bee672b-25-20200228152717.jar:2.0]
Caused by: java.lang.NoClassDefFoundError: com/alicp/jetcache/redis/lettuce/RedisLettuceCacheBuilder
	at com.alicp.jetcache.autoconfigure.RedisLettuceAutoConfiguration$RedisLettuceAutoInit.initCache(RedisLettuceAutoConfiguration.java:111) ~[jetcache-autoconfigure-2.5.14.jar!/:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.process(AbstractCacheAutoInit.java:68) ~[jetcache-autoconfigure-2.5.14.jar!/:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.afterPropertiesSet(AbstractCacheAutoInit.java:49) ~[jetcache-autoconfigure-2.5.14.jar!/:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.alicp.jetcache.redis.lettuce.RedisLettuceCacheBuilder
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_231]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93) ~[user-center-6bee672b-25-20200228152717.jar:2.0]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_231]
	... 29 common frames omitted

**Comment by XyCodeer** [comment]
<dependency>
   		   <groupId>com.alicp.jetcache</groupId>
    	   <artifactId>jetcache-starter-redis</artifactId>
    	   <version>2.5.14</version>
        </dependency>
		<dependency>
			<groupId>com.alicp.jetcache</groupId>
			<artifactId>jetcache-redis-lettuce</artifactId>
			<version>2.5.9</version>
		</dependency>

**Comment by areyouok** [comment]
你的依赖不对，首先jetcache两个组件的版本要一样，第二你应该依赖jetcache-starter-redis-lettuce，关于要依赖哪个Wiki的Home页面有写。

**Comment by duocoding** [comment]
您好，我的redis是以集群部署在服务器上面的，使用此方式redis://password@host:port方式在yml中，有个问题是我的密码里面包含@字符，现在启动就会报错，现在除了修改密码，还有其他办法吗？

**Comment by zhoujibo** [comment]
> 您好，我的redis是以集群部署在服务器上面的，使用此方式redis://password@host:port方式在yml中，有个问题是我的密码里面包含@字符，现在启动就会报错，现在除了修改密码，还有其他办法吗？

用UrlEncode转义一下密码试试看，‘@’会被转义为%40
