### ISSUE TITLE
在yml中配置limit，比如配置了2147483647，初始化缓存后put一下就内存溢出，这是正常的吗？

### ISSUE THREAD

**Issue by zhanghonglei1015** [alibaba/jetcache#523]
在yml中配置limit，比如配置了2147483647，初始化缓存后就内存溢出，这是正常的吗？缓存还没有放入任何数据
感谢解答~

**Comment by liu844869663** [comment]
我试了一下不会吧，有图？

**Comment by zhanghonglei1015** [comment]
> 我试了一下不会吧，有图？

呃。。信息有误，是初始化没事，初始化完了get也没事，put一下就挂：cache.put("fdsa", "fds");

`java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:704)
	at java.util.HashMap.putVal(HashMap.java:629)
	at java.util.HashMap.put(HashMap.java:612)
	at com.alicp.jetcache.embedded.LinkedHashMapCache$LRUMap.putValue(LinkedHashMapCache.java:108)
	at com.alicp.jetcache.embedded.AbstractEmbeddedCache.do_PUT(AbstractEmbeddedCache.java:97)
	at com.alicp.jetcache.AbstractCache.PUT(AbstractCache.java:262)
	at com.alicp.jetcache.external.MockRemoteCache.do_PUT(MockRemoteCache.java:136)
	at com.alicp.jetcache.AbstractCache.PUT(AbstractCache.java:262)
	at com.alicp.jetcache.Cache.PUT(Cache.java:364)
	at com.alicp.jetcache.Cache.put(Cache.java:74)
	at com.alicp.jetcache.SimpleProxyCache.put(SimpleProxyCache.java:43)
	at com.alicp.jetcache.anno.field.LazyInitCache.put(LazyInitCache.java:146)
	at com.noswil.ua.StartupInitialize.run(StartupInitialize.java:63)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.noswil.Application.main(Application.java:18)`

**Comment by liu844869663** [comment]
你设置的太大了，调小一点，不然HashMap无法分配这么大的空间（localLimit*1.4f）

**Comment by zhanghonglei1015** [comment]
> 你设置的太大了，调小一点，不然HashMap无法分配这么大的空间（localLimit*1.4f）

其实我是想问，这个空间是预分配的吗，只要put一下，就一下子分配了那么多空间，而不是随着key的增长逐渐占用

**Comment by liu844869663** [comment]
> 预分配的吗

你设置了localLimit，jetcache给你缓存实例设置的HashMap初始容量就是localLimit*1.4f，本地缓存类型你可以使用caffeine类型

**Comment by zhanghonglei1015** [comment]
> > 预分配的吗
> 
> 你设置了localLimit，jetcache给你缓存实例设置的HashMap初始容量就是localLimit*1.4f，本地缓存类型你可以使用caffeine类型

明白了，linkhashmap是这样，caffeine没有问题，感谢感谢！
