### ISSUE TITLE
com.alicp.jetcache.support.CacheEncodeException: decode error求解

### ISSUE THREAD

**Issue by yangzhenning** [alibaba/jetcache#536]
1：任何对象都实例化
2：同一个接口，99%情况下不会报错，1%就会，而且是class not found，何解？

2020-11-12 19:14:26,067|ForkJoinPool.commonPool-worker-3||ERROR|com.alicp.jetcache.AbstractCache|logError|jetcache(RedisCache) GET error. key=413802036.
com.alicp.jetcache.support.CacheEncodeException: decode error
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:46) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:11) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.redis.RedisCache.do_GET(RedisCache.java:111) ~[jetcache-redis-2.5.14.jar!/:?]
        at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:87) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.MultiLevelCache.do_GET(MultiLevelCache.java:88) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:87) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:140) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.RefreshCache.computeIfAbsent(RefreshCache.java:61) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.RefreshCache.computeIfAbsent(RefreshCache.java:56) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:245) ~[jetcache-anno-2.5.14.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:92) ~[jetcache-anno-2.5.14.jar!/:?]
        at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:84) ~[jetcache-anno-2.5.14.jar!/:?]
        at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:74) ~[jetcache-anno-2.5.14.jar!/:?]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at com.united.apps.sdc.core.service.impl.QueryShipServiceImpl$$EnhancerBySpringCGLIB$$28263c05.getShipStaticByMMSI(<generated>) ~[sdc-core-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at com.united.apps.sdc.core.service.impl.ShipPositionChangeServiceImpl.lambda$changeHandle$0(ShipPositionChangeServiceImpl.java:108) ~[sdc-core-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
        at com.united.apps.sdc.core.service.impl.ShipPositionChangeServiceImpl.lambda$changeHandle$1(ShipPositionChangeServiceImpl.java:81) ~[sdc-core-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at com.united.apps.sdc.core.service.impl.ShipPositionChangeServiceImpl.lambda$changeHandle$2(ShipPositionChangeServiceImpl.java:72) ~[sdc-core-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[?:?]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[?:?]
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[?:?]
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[?:?]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[?:?]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.alicp.jetcache.CacheValueHolder
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.springframework.util.ClassUtils.forName(ClassUtils.java:275) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at org.springframework.core.ConfigurableObjectInputStream.resolveClass(ConfigurableObjectInputStream.java:76) ~[spring-core-5.1.2.RELEASE.jar!/:5.1.2.RELEASE]
        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1965) ~[?:?]
        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1851) ~[?:?]
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2139) ~[?:?]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1668) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:482) ~[?:?]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:440) ~[?:?]
        at com.alicp.jetcache.support.JavaValueDecoder.doApply(JavaValueDecoder.java:29) ~[jetcache-core-2.5.14.jar!/:?]
        at com.alicp.jetcache.support.AbstractValueDecoder.apply(AbstractValueDecoder.java:41) ~[jetcache-core-2.5.14.jar!/:?]
        ... 27 more

**Comment by he037** [comment]
遇到和上面描述一样的问题
我这边遇到的原因是：返回值对象里面新增了字段，在发布上线后，gray环境有新加字段，正式环境没有，两边同时在操作，gray新加字段的返回值插入到redis后，正式环境查询相同的key，redis解析失败，所以我这边还是业务代码问题
