### ISSUE TITLE
在一个项目中使用@Cached, 在另一个项目中使用@CacheInvalidate 报错. can't find @Cached definition with area=default

### ISSUE THREAD

**Issue by siaron** [alibaba/jetcache#572]
在一个项目中使用
```
@Cached(name = "rolePermission:", key = "#roleId", expire = 3600 * 24, cacheType = CacheType.REMOTE)
```
进行缓存.
在另一个项目中使用
```
@CacheInvalidate(name = "rolePermission:", key = "#menuPrivilegeAo.roleId")
```
报错
```

2021-04-07 15:30:29.877 ERROR 94099 [eu9l7Nqp] [XNIO-1 task-1] com.alicp.jetcache.anno.support.CacheContext Cache operation aborted because can't find @Cached definition

com.alicp.jetcache.CacheConfigException: can't find @Cached definition with area=default name=rolePermission:, specified in public int com.xxx.iotcloud.system.application.service.impl.SysRoleServiceImpl.updateRoleMenuPrivilege(com.xxx.iotcloud.system.api.ao.role.SysRoleMenuPrivilegeEditAo)
	at com.alicp.jetcache.anno.support.CacheContext.lambda$createCacheInvokeContext$0(CacheContext.java:61)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvalidate(CacheHandler.java:143)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvalidate(CacheHandler.java:138)
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithInvalidateOrUpdate(CacheHandler.java:107)
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:95)
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:85)
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:80)
```

**Comment by siaron** [comment]
```
    public void putByMethodInfo(String key, CacheInvokeConfig config) {
        methodInfoMap.put(key, config);
        CachedAnnoConfig cac = config.getCachedAnnoConfig();
        if (cac != null && !CacheConsts.isUndefined(cac.getName())) {
            cacheNameMap.put(cac.getArea() + "_" + cac.getName(), config);
        }
    }
```
这个方法`invalidateAnnoConfigs`这个没有处理码?

**Comment by enkeshu** [comment]
遇见了相同的问题
