### ISSUE TITLE
SpringBoot2.0.1 maven项目，引入jetcache包，启动报错

### ISSUE THREAD

**Issue by asf-cache** [alibaba/jetcache#64]
Dear all，我遇到一个项目启动报错的问题如下：

一、SpringBoot2.0 项目启动问题
我的项目没有配置数据源连接池、一个非常简单干净的springboot项目，引入jetcache包报错如下：（去掉jetcache包就能正常启动）

gradle配置文件引入的代码：
compile('com.alicp.jetcache:jetcache-starter-redis-lettuce:2.5.0')

启动报错的主要日志：
o.s.b.diagnostics.FailureAnalyzers : FailureAnalyzer org.springframework.boot.autoconfigure.jdbc.HikariDriverConfigurationFailureAnalyzer@1473b8c0 failed java.lang.TypeNotPresentException: Type org.springframework.jdbc.CannotGetJdbcConnectionException not present at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117) at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125) at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68) at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138) at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49) at sun.reflect.generics.repository.ClassRepository.getSuperclass(ClassRepository.java:90)

----------------
jetcache依赖数据库？

二、关于redis客户端选择问题，我的项目如果使用jetcache希望既可以使用lettuce又能使用jedis，如何解决？

**Comment by areyouok** [comment]
jetcache的单元测试能在spring 5.0.4.RELEASE + boot 2.0.0.RELEASE下通过。但是jetcache当前版本摹人传递的依赖是spring 4 + boot 1.5的，你应该检查一下你的依赖树，是不是有低版本的jar被导入进去。

第二个问题我认为单用lettuce就很好。如果非要两个一起中，需要配置两份，通过area来区分。

**Comment by asf-cache** [comment]
额，我又尝试了最新的2.5.1，也确认了引入的jar包没有底版本的问题，依然有错误：
Error creating bean with name 'redisAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisAutoConfiguration.class]: Post-processing of merged bean definition failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.alicp.jetcache.autoconfigure.RedisAutoConfiguration$RedisAutoInit] from ClassLoader [sun.misc.Launcher$AppClassLoader@18b4aac2]
------可能我的配置文件格式不对：（望指点）
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: caffeine
      limit: 100
      keyConvertor: fastjson
      expireAfterWriteInMillis: 86400000
    otherArea:
      type: linkedhashmap
      limit: 100
      keyConvertor: none
      expireAfterAccessInMillis: 3600000
  remote:
    default:
      type: redis.lettuce
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri:
        - redis://10.10.69.16:6389
        - redis://10.10.69.16:6399
        - redis://10.10.69.16:6369
    otherArea:
      type: redis
      keyConvertor: fastjson
      valueEncoder: kryo
      valueDecoder: kryo
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 10.10.69.16
      port: 6379

**Comment by asf-cache** [comment]
配置文件的空格都被默认去掉了，尴尬

**Comment by areyouok** [comment]
一时看不出有什么问题，不过你肯定什么地方搞错了。jetcache-test里面的很多单元测试可以作为例子，你可以看一下。

markdown的语法了解一下。代码用三个`包起来，就能保留原始格式了。

**Comment by teli5200** [comment]
一样有这个问题，尴尬。。。到底怎么处理

**Comment by teli5200** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisAutoInit' defined in class path resource [com/alicp/jetcache/autoconfigure/RedisAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: com/alicp/jetcache/redis/RedisCacheBuilder

**Comment by chenkaiwei** [comment]
如果还有哪位兄弟遇到这个问题我这里有个解决思路：
配置部分的规则和jedis不一样，改成
remote:
    default:
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri:
        uri: redis://${spring.redis.host}:${spring.redis.port}/${spring.redis.database}
就好了。

**Comment by chenkaiwei** [comment]
> 如果还有哪位兄弟遇到这个问题我这里有个解决思路： 配置部分的规则和jedis不一样，改成 remote: default: poolConfig: minIdle: 5 maxIdle: 20 maxTotal: 50 uri: uri: redis://${spring.redis.host}:${spring.redis.port}/${spring.redis.database} 就好了。

自己确认了下，还是不行，启动不报错了但是运行中会连不上。目前只能不要用lettuce了，用jedis就完全没问题。
