### ISSUE TITLE
jetcache-redis-lettuce 不支持 expireAfterAccess特性，缓存访问后 expire时间刷新，是否只能通过refreshPolicy实现呢？

### ISSUE THREAD

**Issue by hnwlxywns** [alibaba/jetcache#655]
在使用jetcache-redis-lettuce时，当设置 expireAfterAccess 参数后，会报异常：
`
Caused by: com.alicp.jetcache.CacheConfigException: expireAfterAccess is not supported
	at com.alicp.jetcache.redis.lettuce.RedisLettuceCache.<init>(RedisLettuceCache.java:51)
	at com.alicp.jetcache.redis.lettuce.RedisLettuceCacheBuilder.lambda$new$0(RedisLettuceCacheBuilder.java:21)
	at com.alicp.jetcache.AbstractCacheBuilder.buildCache(AbstractCacheBuilder.java:43)
	at cn.trustway.nix.boot.cache.configuration.NixCacheAutoConfiguration.globalRemoteCache(NixCacheAutoConfiguration.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 20 common frames omitted
`
请教一下，如何让缓存访问后，expire失效时间，能够刷新expire时间？

**Comment by areyouok** [comment]
redis里面的，等超时了重新load吧。你要在每次读的时候去更新超时时间，那不是引入了很多写么
