### ISSUE TITLE
jedis 需要 4.2.3 版本 么 spring boot 2.7.3 默认依赖jedis版本是3.8.0 使用时会报找不到redis/clients/jedis/commands/StringBinaryCommands错误

### ISSUE THREAD

**Issue by wushujia789** [alibaba/jetcache#706]

**Comment by areyouok** [comment]
看文档，需要新版jedis。 spring-data默认用的lettuce，如果你的spring-data没用jedis可以自己手工把jedis升级一下。

**Comment by wushujia789** [comment]
按文档
https://github.com/alibaba/jetcache/blob/master/docs/CN/RedisWithLettuce.md

不使用spring boot  的配置
出现如下错误

Caused by: com.alicp.jetcache.CacheConfigException: PubSubConnection not set
	at com.alicp.jetcache.redis.lettuce.LettuceBroadcastManager.<init>(LettuceBroadcastManager.java:43) ~[jetcache-redis-lettuce-2.7.0.jar:?]
	at com.alicp.jetcache.redis.lettuce.RedisLettuceCacheBuilder.createBroadcastManager(RedisLettuceCacheBuilder.java:43) ~[jetcache-redis-lettuce-2.7.0.jar:?]
	at com.alicp.jetcache.template.NotifyMonitorInstaller.addMonitors(NotifyMonitorInstaller.java:45) ~[jetcache-core-2.7.0.jar:?]
	at com.alicp.jetcache.SimpleCacheManager.create(SimpleCacheManager.java:148) ~[jetcache-core-2.7.0.jar:?]
	at com.alicp.jetcache.SimpleCacheManager.lambda$getOrCreateCache$4(SimpleCacheManager.java:110) ~[jetcache-core-2.7.0.jar:?]
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[?:1.8.0_221]
	at com.alicp.jetcache.SimpleCacheManager.getOrCreateCache(SimpleCacheManager.java:110) ~[jetcache-core-2.7.0.jar:?]

**Comment by areyouok** [comment]
你用lettuce为什么会和spring boot冲突呢

**Comment by wushujia789** [comment]
后来换成普通spring 工程了。

**Comment by wushujia789** [comment]
发现问题了使用了lettuce后不能使用CacheManager 
@Autowired
private CacheManager cacheManager;

**Comment by rewin58** [comment]
出现“Caused by: com.alicp.jetcache.CacheConfigException: PubSubConnection not set” 问题解决了吗？

我是在spring boot 工程中，因为jetcache没有提供批量删除多个cacheName的注解，我扩展了注解，提供删除的方法，需要获取RedisClient。

所以按照https://github.com/alibaba/jetcache/blob/master/docs/CN/RedisWithLettuce.md 文档继承了jetcache，在构建GlobalCacheConfig bean时，如果设置broadcastChannel属性，就会报PubSubConnection not set这个错误，不设置不会报错
remoteCacheBuilder.broadcastChannel(broadcastChannel);
