### ISSUE TITLE
懒加载属性，读取缓存后执行序列化产生异常

### ISSUE THREAD

**Issue by belllee** [alibaba/jetcache#9]
当实体中存在懒加载属性的时候，读取缓存的对象后，进行序列化操作，会产生异常。
属性定义：
```
@OneToMany(mappedBy="topic",fetch = FetchType.LAZY)
	public List<TopicTags> getTopicTags() {
		return topicTags;
	}
```
序列化操作：
        ```
@Override
	public void serialize(Result value, JsonGenerator jgen, SerializerProvider provider)
			throws IOException, JsonProcessingException {

		jgen.writeStartObject();
		jgen.writeStringField("result", value.getResult().toString());
		jgen.writeNumberField("code", value.getCode());
		jgen.writeStringField("reason", value.getReason());		
		jgen.writeFieldName("content");
		jgen.writeStartArray();
		for (Object obj : value.getContent()) {
			objectWriter.writeValue(jgen, obj);
		}
		jgen.writeEndArray();
		jgen.writeEndObject();

	}
```
异常信息：
```
org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: com.my.wxcop.entity.topic.Topic.topicTags, could not initialize proxy - no Session
	at org.hibernate.collection.internal.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:576)
	at org.hibernate.collection.internal.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:215)
	at org.hibernate.collection.internal.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:156)
	at org.hibernate.collection.internal.PersistentBag.size(PersistentBag.java:278)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:101)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:24)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:693)
	at com.fasterxml.jackson.databind.ser.impl.FilteredBeanPropertyWriter$SingleView.serializeAsField(FilteredBeanPropertyWriter.java:67)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:675)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
	at com.my.common.editor.ResultSerializer.serialize(ResultSerializer.java:59)
	at com.my.common.editor.ResultSerializer.serialize(ResultSerializer.java:17)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1387)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:889)
```

**Comment by areyouok** [comment]
懒加载的属性，请先显式加载以后再往缓存里面放。

**Comment by belllee** [comment]
多谢，显示加载后没有这个错误了。
