### ISSUE TITLE
加锁时线程池溢出异常，生产环境，麻烦帮忙看一下

### ISSUE THREAD

**Issue by Skqing** [alibaba/jetcache#906]
jetcache版本：2.7.3

```
ERROR [io.netty.util.concurrent.DefaultPromise.safeExecute: 864] - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:934) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:351) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:344) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:836) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute0(SingleThreadEventExecutor.java:827) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:817) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:862) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:500) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:185) ~[netty-common-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95) ~[netty-transport-4.1.89.Final.jar!/:4.1.89.Final]
        at io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30) ~[netty-transport-4.1.89.Final.jar!/:4.1.89.Final]
        at io.lettuce.core.protocol.DefaultEndpoint.writeToChannelAndFlush(DefaultEndpoint.java:382) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.protocol.DefaultEndpoint.write(DefaultEndpoint.java:196) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.writeCommand(ClusterDistributionChannelWriter.java:238) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.writeCommand(ClusterDistributionChannelWriter.java:224) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.doWrite(ClusterDistributionChannelWriter.java:173) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.cluster.ClusterDistributionChannelWriter.write(ClusterDistributionChannelWriter.java:103) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.RedisChannelHandler.dispatch(RedisChannelHandler.java:191) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl.dispatch(StatefulRedisClusterConnectionImpl.java:215) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.AbstractRedisAsyncCommands.dispatch(AbstractRedisAsyncCommands.java:627) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at io.lettuce.core.AbstractRedisAsyncCommands.get(AbstractRedisAsyncCommands.java:871) ~[lettuce-core-6.1.10.RELEASE.jar!/:6.1.10.RELEASE]
        at com.alicp.jetcache.redis.lettuce.RedisLettuceCache.do_GET(RedisLettuceCache.java:164) ~[jetcache-redis-lettuce-2.7.3.jar!/:?]
        at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:83) ~[jetcache-core-2.7.3.jar!/:?]
        at com.alicp.jetcache.Cache.tryLock(Cache.java:226) ~[jetcache-core-2.7.3.jar!/:?]
```

**Comment by areyouok** [comment]
这个是你lettuce client关闭了吧

**Comment by Skqing** [comment]
> 这个是你lettuce client关闭了吧

看日志像是获取锁的时候添加监听器的线程池溢出了，如果是lettuce client关闭了应该不是这个异常吧，lettuce client关闭不应该是连接异常吗？

**Comment by areyouok** [comment]
你看异常消息，event executor terminated，redis client里面的netty executor关闭了，这个只能你自己查了

**Comment by Skqing** [comment]
> 你看异常消息，event executor terminated，redis client里面的netty executor关闭了，这个只能你自己查了

哦哦，看这里的话确实可能关闭了，不过关闭了之后线程池溢出确实奇怪，我们查一下看看。

**Comment by Skqing** [comment]
> lettuce client

有点奇怪的是，如果lettuce client关闭了不是所有连接都中断了，但实际情况是生产上不是所有连接都中断，部分操作又是可以的，有的奇怪。

**Comment by Skqing** [comment]
https://github.com/redis/lettuce/issues/1773
看来别人之前也遇到过这样的问题

**Comment by Roiocam** [comment]
> ERROR [io.netty.util.concurrent.DefaultPromise.safeExecute: 864] - Failed to submit a listener notification task. Event loop shut down?

不是 Lettuce Client 关闭，而是 Lettuce 底层的 Executor 关闭了，但 IO Thread 还在活跃吧
