### ISSUE TITLE
redis密码配置无效

### ISSUE THREAD

**Issue by zpandasoft** [alibaba/jetcache#917]
配置了redis密码，但在使用时还报未设置密码
配置如下：
  remote:
    default: #default表示全部生效，也可以指定某个cacheName
      type: redis
#      redissonClient: redisClientBeanName
      # key转换器方式n
      keyConvertor: fastjson
      broadcastChannel: projectA
      # redis序列化方式
      valueEncoder: java
      valueDecoder: java
      # redis线程池
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
        # redis地址与端口
      host: 192.168.103.253
      port: 6379
      password: 123456

maven 如下：
          <dependency>
            <groupId>com.alicp.jetcache</groupId>
            <artifactId>jetcache-starter-redis</artifactId>
            <version>2.7.6</version>
        </dependency>

        
        <dependency>
            <groupId>redis.clients</groupId>
            <artifactId>jedis</artifactId>
            <version>4.3.1</version>
        </dependency>
        
报错信息如下：

redis.clients.jedis.exceptions.JedisDataException: ERR Client sent AUTH, but no password is set
	at redis.clients.jedis.Protocol.processError(Protocol.java:96) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Protocol.process(Protocol.java:137) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Protocol.read(Protocol.java:192) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:316) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:243) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Connection.auth(Connection.java:372) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:345) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Connection.<init>(Connection.java:53) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.Jedis.<init>(Jedis.java:214) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:181) ~[jedis-4.3.1.jar:na]
	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223) ~[commons-pool2-2.11.1.jar:2.11.1]
	at redis.clients.jedis.util.Pool.getResource(Pool.java:34) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:373) ~[jedis-4.3.1.jar:na]
	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:17) ~[jedis-4.3.1.jar:na]
	at com.alicp.jetcache.redis.RedisCache.writeCommands(RedisCache.java:141) ~[jetcache-redis-2.7.6.jar:na]
	at com.alicp.jetcache.redis.RedisCache.readCommands(RedisCache.java:146) ~[jetcache-redis-2.7.6.jar:na]
	at com.alicp.jetcache.redis.RedisCache.do_GET(RedisCache.java:195) ~[jetcache-redis-2.7.6.jar:na]
	at com.alicp.jetcache.AbstractCache.GET(AbstractCache.java:88) [jetcache-core-2.7.6.jar:na]
	at com.alicp.jetcache.AbstractCache.computeIfAbsentImpl(AbstractCache.java:150) [jetcache-core-2.7.6.jar:na]
	at com.alicp.jetcache.AbstractCache.computeIfAbsent(AbstractCache.java:119) [jetcache-core-2.7.6.jar:na]
	at com.alicp.jetcache.Cache.computeIfAbsent(Cache.java:312) [jetcache-core-2.7.6.jar:na]
	at com.alicp.jetcache.anno.method.CacheHandler.invokeWithCached(CacheHandler.java:264) [jetcache-anno-2.7.6.jar:na]
	at com.alicp.jetcache.anno.method.CacheHandler.doInvoke(CacheHandler.java:107) [jetcache-anno-2.7.6.jar:na]
	at com.alicp.jetcache.anno.method.CacheHandler.invoke(CacheHandler.java:99) [jetcache-anno-2.7.6.jar:na]
	at com.alicp.jetcache.anno.aop.JetCacheInterceptor.invoke(JetCacheInterceptor.java:91) [jetcache-anno-2.7.6.jar:na]

**Comment by areyouok** [comment]
相关代码是RedisAutoConfiguration，自己看看缺什么吧

**Comment by zpandasoft** [comment]
这个很早就看过了 用的 JedisPool  且 host port  password都正确

**Comment by zpandasoft** [comment]
> 相关代码是RedisAutoConfiguration，自己看看缺什么吧

这个很早就看过了 用的 JedisPool 且 host port password都正确
