### ISSUE TITLE
希望支持配置文件${}占位符

### ISSUE THREAD

**Issue by charlesvhe** [alibaba/jetcache#97]
希望支持如下配置
```
# Redis配置
spring.redis.host=127.0.0.1
spring.redis.port=6379

# JetCache配置
jetcache.areaInCacheName=false
jetcache.local.default.type=caffeine
jetcache.local.default.keyConvertor=fastjson
jetcache.remote.default.type=redis.lettuce
jetcache.remote.default.uri=redis://${spring.redis.host}:${spring.redis.port}/
jetcache.remote.default.keyConvertor=fastjson
jetcache.remote.default.valueEncoder=kryo
jetcache.remote.default.valueDecoder=kryo
```

**Comment by xryg2276287715** [comment]
个人觉得这个没必要吧。万一配置项对应的value里面${}本身就是合法字符串怎么办？

**Comment by charlesvhe** [comment]
spring boot的潮流呀，基于spring的很多组件都支持

**Comment by areyouok** [comment]
现在不是可以么？

**Comment by xryg2276287715** [comment]
原来boot支持properties文件这样配置哇，平时都没怎么用这种配置方式。哈哈~

**Comment by charlesvhe** [comment]
配置：
# Redis配置
spring.redis.host=192.168.30.56
spring.redis.port=6379

# JetCache配置
jetcache.areaInCacheName=false
jetcache.local.default.type=caffeine
jetcache.local.default.keyConvertor=fastjson
jetcache.remote.default.type=redis.lettuce
jetcache.remote.default.uri=redis://${spring.redis.host}:${spring.redis.port}/
jetcache.remote.default.keyConvertor=fastjson
jetcache.remote.default.valueEncoder=kryo
jetcache.remote.default.valueDecoder=kryo

报错：
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-06-22 13:43:55.302 ERROR 11288 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'redisLettuceAutoInit': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Illegal character in authority at index 8: redis://${spring.redis.host}:${spring.redis.port}/
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:138) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:424) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1700) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:581) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:503) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.yryz.backend.ApplicationYryzBackend.main(ApplicationYryzBackend.java:26) [classes/:na]
Caused by: java.lang.IllegalArgumentException: Illegal character in authority at index 8: redis://${spring.redis.host}:${spring.redis.port}/
	at java.net.URI.create(URI.java:852) ~[na:1.8.0_172]
	at io.lettuce.core.RedisURI.create(RedisURI.java:250) ~[lettuce-core-5.0.4.RELEASE.jar:na]
	at io.lettuce.core.RedisClient.create(RedisClient.java:135) ~[lettuce-core-5.0.4.RELEASE.jar:na]
	at com.alicp.jetcache.autoconfigure.RedisLettuceAutoConfiguration$RedisLettuceAutoInit.initCache(RedisLettuceAutoConfiguration.java:56) ~[jetcache-autoconfigure-2.5.2.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.process(AbstractCacheAutoInit.java:72) ~[jetcache-autoconfigure-2.5.2.jar:na]
	at com.alicp.jetcache.autoconfigure.AbstractCacheAutoInit.init(AbstractCacheAutoInit.java:53) ~[jetcache-autoconfigure-2.5.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_172]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_172]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_172]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_172]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:365) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:308) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:135) ~[spring-beans-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	... 18 common frames omitted
Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: redis://${spring.redis.host}:${spring.redis.port}/
	at java.net.URI$Parser.fail(URI.java:2848) ~[na:1.8.0_172]
	at java.net.URI$Parser.parseAuthority(URI.java:3186) ~[na:1.8.0_172]
	at java.net.URI$Parser.parseHierarchical(URI.java:3097) ~[na:1.8.0_172]
	at java.net.URI$Parser.parse(URI.java:3053) ~[na:1.8.0_172]
	at java.net.URI.<init>(URI.java:588) ~[na:1.8.0_172]
	at java.net.URI.create(URI.java:850) ~[na:1.8.0_172]
	... 30 common frames omitted

去掉placeholder可以正常启动

**Comment by areyouok** [comment]
我在yml里面试过是可以的。你的变量定义和使用在一个文件里面吗？

**Comment by charlesvhe** [comment]
参考问题重现代码：
[jetcache.zip](https://github.com/alibaba/jetcache/files/2127629/jetcache.zip)

**Comment by areyouok** [comment]
感谢！

**Comment by wangzhanz** [comment]
变量定义在系统变量里面，如果使用@ConfigurationProperties是可以取到的，但是jetCache初始化时候无法获取到，是不是跟springboot的生命周期有关？
